source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ProjetoMentoria' do
  # Pods for ProjetoMentoria
  pod 'Alamofire', '~> 4.4.0'

  target 'ProjetoMentoriaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjetoMentoriaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
